//
//  LoginScreenPresenter.swift
//  LoginScreen
//
//  Created Z on 1/16/20.
//  Copyright © 2020 Zyma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LoginScreenPresenter: LoginScreenPresenterProtocol {

    weak private var view: LoginScreenViewProtocol?
    var interactor: LoginScreenInteractorProtocol?
    private let router: LoginScreenWireframeProtocol

    init(interface: LoginScreenViewProtocol, interactor: LoginScreenInteractorProtocol?, router: LoginScreenWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
