//
//  LoginScreenProtocols.swift
//  LoginScreen
//
//  Created Z on 1/16/20.
//  Copyright © 2020 Zyma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol LoginScreenWireframeProtocol: class {

}
//MARK: Presenter -
protocol LoginScreenPresenterProtocol: class {

}

//MARK: Interactor -
protocol LoginScreenInteractorProtocol: class {

  var presenter: LoginScreenPresenterProtocol?  { get set }
}

//MARK: View -
protocol LoginScreenViewProtocol: class {

  var presenter: LoginScreenPresenterProtocol?  { get set }
}
